Story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib.auth import views
from Story9.views import index

app_name = 'Story9'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('StoryTDD.urls')),
    path('story9/', include(('Story9.urls', 'Story9'), namespace="Story9")),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('story9/', index, name='index'),
]

Story9/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib.auth import views
from django.conf import settings
from .views import *

urlpatterns = [   
    path('', index, name='index'),
    path('get-book/', get_book, name="get_book"),
    path('tambah', tambah, name="tambah"),
	path('kurang', kurang, name="kurang"),
    path('login/', loginnya, name="login"),
    path('logout/', logoutPage, name="logout")
]


#856446014234-76fc0h955oifrq923i9biuhu7oducqpb.apps.googleusercontent.com id

#-3ZKidUeJdm9xwn09PstxEsH secret

StoryTDD/urls.py
from django.urls import path
from .views import *

urlpatterns = [   
    path('', index, name='landing_page'),
    path('profile', profile, name="showprofile"),
    path('cekemail/', cek_email, name="cekemail"),
    path('addsubs/', add_subs, name="addsubs"),
    path('get_subs_url', getsubs, name="getsubs")
]

Story9/models.py
from django.db import models

# Create your models here.

StoryTDD/models.py
from django.db import models

class Status(models.Model):
    statusnya = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)

class Subscriber(models.Model):
    nama = models.CharField(max_length=40)
    email = models.EmailField()
    password = models.CharField(max_length=20)

# Create your models here.

Story9/forms.py
from django import forms

class Search_Form(forms.Form):
    attrs = {
        'class': 'form-control',
        'placeholder': 'Keyword'
    }

    keyword = forms.CharField(label='Search', required=True, max_length=300, widget=forms.TextInput(attrs=attrs))

StoryTDD/forms.py
from django import forms

class Status_Form(forms.Form):
    attrs = {
        'class': 'form-control',
        'placeholder': 'Statusmu!'
    }

    statusnya = forms.CharField(label='Statusmu', required=True, max_length=300, widget=forms.TextInput(attrs=attrs))

class Subs_Form(forms.Form):
    attrsname = {
        'class' : 'form-control',
        'placeholder' : 'Masukan namamu',
        'id' : 'formNama'
    }

    attrsemail = {
        'class' : 'form-control',
        'placeholder' : 'Masukan emailmu',
        'id' : 'formEmail'
    }

    attrspassword = {
        'class' : 'form-control',
        'placeholder' : 'Masukan password',
        'type' : 'password',
        'id' : 'formPassword'
    }

    email = forms.EmailField(label='Email', required=True, max_length=30, widget=forms.TextInput(attrs=attrsemail))
    name = forms.CharField(label='Nama', required=True, max_length=40, widget=forms.TextInput(attrs=attrsname))
    password = forms.CharField(label='Password', required=True, max_length=30, widget=forms.TextInput(attrs=attrspassword))

Story9/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.core import serializers

from .forms import Search_Form
from django.views.decorators.csrf import csrf_exempt
import requests


def get_book(request):
    listbuku['status_code'] = 200
    if request.user.is_authenticated:
        count = request.session.get('counter', 0)
        request.session['counter'] = count
        for key, value in request.session.items():
            print('{} => {}'.format(key, value))
        
    return JsonResponse(listbuku)

@csrf_exempt
def index(request):
    response={}
    if request.user.is_authenticated:
        request.session['first_name'] = request.user.first_name
        request.session['last_name'] = request.user.last_name
        request.session['email'] = request.user.email
        if ('counter' in request.session.keys()):
            request.session['counter'] = request.session['counter']
            response['counter'] = request.session['counter']
        else:
            request.session['counter'] = 0
            response['counter'] = 0
        for key, value in request.session.items():
            print('{} => {}'.format(key, value))

    else:
        response['counter'] = 0
        
    response['searchform'] = Search_Form
    form = Search_Form(request.GET)
    global listbuku 


    if form.is_valid():   
        url = "https://www.googleapis.com/books/v1/volumes?q="
        url += request.GET['keyword']
        listbuku = requests.get(url).json()
        return render(request, 'index.html', response)
    else:
        url = "https://www.googleapis.com/books/v1/volumes?q=quilting"
        listbuku = requests.get(url).json()
        return render(request, 'index.html', response)

def loginnya(request):
    return render(request, 'login.html')

def tambah(request):
	request.session['counter'] = request.session['counter'] + 1
	return HttpResponse(request.session['counter'], content_type = "application/json")

def kurang(request):
	request.session['counter'] = request.session['counter'] - 1
	return HttpResponse(request.session['counter'], content_type = "application/json")

def logoutPage(request):
	request.session.flush()
	logout(request)
	return HttpResponseRedirect('/story9')

StoryTDD/views.py
from django.shortcuts import render
from .models import Status, Subscriber
from .forms import Status_Form, Subs_Form
from django.http import HttpResponseRedirect
from django.http import JsonResponse

def index(request):
    response = {}
    response['statusform'] = Status_Form

    allstatus = Status.objects.all()
    response['showstatus'] = allstatus
    form = Status_Form(request.POST)
    if request.method == 'POST' and form.is_valid():
        response['statusnya'] = request.POST['statusnya']   
        status = Status(statusnya=response['statusnya'])
        status.save()
        return render(request, 'landing_page.html', response)
    else:
        return render(request, 'landing_page.html', response)

def profile(request):
    response = {}
    response['subsform'] = Subs_Form
    return render(request, "profile.html", response)

def cek_email(request):
    tempCheck = Subscriber.objects.filter(email=request.POST['email'])

    if tempCheck:
        return JsonResponse({
            'pesan':'Email telah terpakai',
            'status':'fail'
        })
    
    return JsonResponse({
        'pesan':'Email bisa digunakan',
        'status':'success'
    })

def add_subs(request):
    if (request.method == "POST"):
        subscriber = Subscriber(
            email = request.POST['email'],
            nama = request.POST['name'],
            password = request.POST['password']   
        )
        subscriber.save()
        return JsonResponse({
            'pesan':'Selamat And telah Subscribe ke Website ini!'
        }, status = 200)
    else:
        return JsonResponse({
            'pesan':"Something wrong"
        }, status = 403)

def getsubs(request):
    data = list(Subscriber.objects.values())
    alldata = {
        'data' : data
    }

    return JsonResponse(alldata)

# Create your views here.

Story9/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/stylestory9.css' %}">
    <title>Google Books List</title>
</head>

<body onload="myFunction()" style="margin:0;">
    <div id="loader"></div>
    <div class="container" id="allbooks">
        {% if user.is_authenticated %}
        <div class="text-right" style="font-family: 'Signika', sans-serif; padding-right: 50px;">
            <br>
            <h3>Welcome, {{ user.first_name }} {{ user.last_name }}!</h3>
            <button class="btn btn-danger"><a href="{% url 'Story9:logout' %}" style="color: white">Logout</a></button>
        </div>
        {% else %}
        <div class="text-right" style="font-family: 'Signika', sans-serif; padding-right: 50px;">
            <br>
            <button class="btn btn-danger"><a href="{% url 'social:begin' 'google-oauth2' %}" style="color: white">Login
                    with Google</a></button>
            <br>
        </div>
        {% endif %}


        <h1 class="title font-kayak">Google Books List</h1>
        <h3 class="subtitle" style="display:inline;">Jumlah Favorit:</h3>
        <h3 id="favorited" style="display:inline" class="subtitle">{{ counter }}</h3>
        <div class="container">
            <section name="form">
                <form id="form" method="GET" action="{% url 'Story9:index' %}">
                    {% csrf_token %}
                    {{ searchform }}
                    <button type="submit" class="btn btn-default" id="submitbutton">Submit</button>
                    <br>
                    <br>
                </form>
            </section>
        </div>
        <table class="table">
            <thead>
                <th></th>
                <th>Judul</th>
                <th>Pengarang</th>
                <th>Tanggal Terbit</th>
                <th>Favorit</th>
            </thead>
            <tbody id="list-buku-html">
            </tbody>
        </table>
    </div>

    {% block extrajs %}
    <script type="text/javascript">
        var starafter = "{% static 'img/starafter.png' %}";
        var starbefore = "{% static 'img/starbefore.png' %}";
        var story_9_url = "{% url 'Story9:index' %}";
        var get_book_url = "{% url 'Story9:get_book' %}";
    </script>
    <script type="text/javascript" src="{% static 'js/buku.js' %}"></script>
    {% endblock %}


</body>

</html>

Story9/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/stylestory9.css' %}">

    <title>Login</title>
</head>

<body>

    <h2>Login</h2>
    <br>
    <p><strong>-- OR --</strong></p>
    <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>

</body>

</html>

StoryTDD/templates/landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Hello!</title>
</head>
<body>
    <h1>Hello, Apa kabar?</h1>
    <div class="container" id="btnactivity">
        <section name="form">
                <br>
                <form id="form" method="POST" action="{% url 'landing_page' %}">
                    {% csrf_token %}
                    {{ statusform }}
                    <br>
                    <button type="submit" class="btn btn-default" id="submitbutton">Submit</button>
                </form>
            </section>    
    </div>

    <div class="container" id="allschedule">
        <table class="table">
                <thead>
                    <th>Status</th>
                    <th>Waktu</th>
                </thead>
                <tbody>
                    {% for i in showstatus %}
                    <tr>
                        <td> {{ i.statusnya }} </td>
                        <td> {{ i.created_at }} </td></tr>
                    {% endfor %}
                </tbody>
            </table>      
</div>
</body>
</html>

StoryTDD/templates/profile.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>Home</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/subs.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body onload="myFunction()" style="margin:0;">
<div id="loader"></div>
<div style="display:none;" id="myDiv" class="animate-bottom">
<div class="navbar-frame">
    <nav class="navbar navbar-inverse">
        <div class="BlueNavbar" id="temanavbar">
        <div class="container-fluid">
            <div class="navbar-head er">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'showprofile' %}">Fadhlan's</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'showprofile' %}">Home</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="mailto:fadhlan.permana@gmail.com">Contact Me!</a></li>
                </ul>
            </div>
        </div>
    </div>
    </nav>
</div>
<div class="diatas">
    <div class="container-fluid">
        <h2>Hi, Welcome to my personal Website! </h2>
        <h2>My name is Fadhlan, and currently I'm taking degree in Computer Science at University of Indonesia</h2>
        <a href="https://drive.google.com/open?id=1iP44bz8N7mLp8co85spYbcmfIMI85_z4" class="cv" id="temacv" >Curiculum Vitae</a>
    </div>
    <button type="button" class="btn btn-danger" onclick="change.call(this)" id="buttoncolor">Change Color</button>
</div>

<div class="deskripsi-diri" id="aboutme">
    <div class="container-fluid">
        <div class="media">
            <div class="media-left">
                <a href="http://imgbox.com/ztcWb4rF" target="_blank"><img
                        src="https://thumbs2.imgbox.com/98/36/ztcWb4rF_t.png" alt="image host" class="media-object"></a>
            </div>
            <div class="media-body">
                <h3 id="deskripsidiri">My name is Fadhlan Hafizh Permana, I was born in Jakarta in 1997. </h3>
                <h3 id="deskripsidiri2">My hobby is travelling and culinary, i love to discover local cuisine when i
                    visit a town </h3>
            </div>
        </div>
    </div>
</div>

<div class="accordionqna">
    <div class="container-fluid">
        <h2>Frequently Asked Questions </h2>
        <div id="accordion">
            <h3>Aktivitas</h3>
            <div>
                <p>Kuliah, Bermain, Tidur</p>
            </div>
            <h3>Pengalaman Organisasi/Kepanitiaan</h3>
            <div>
                <li>Stage - Compfest</li>
                <li>PJ LO - Wisuda</li>
                <li>Acara - College Bowl</li>
            </div>
            <h3>Prestasi</h3>
            <div>
                <ul>
                <li>Juara 4 Matematika, UB</li>
                <li>Finalis Olimpiade Online Nasional</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="column">
            <h1>Subscribe to my Website!</h1>
            {% csrf_token %}
            {{ subsform }}
            <div id="statusForm"></div>
            <button class="button" name="submit" id="submit" disabled>Submit</button>
    </div>
    <div class="column">
            <table class="table">
                    <thead>
                        <th>Nama</th>
                    </thead>
                    <tbody id="list-subs-html">
                    </tbody>
                </table>  

    </div>
  </div>

</div>

<!-- {% block extrajs %}
    <script type="text/javascript">
      var get_subs_url = "{% url 'getsubs' %}";
    </script>
{% endblock %} -->

</body>
</html>